Add cgi so I maybe do a better status/analytics page; remove repoctl ignores as now it defaults to ignore when not found in AUR; leave code commented on chaotic-add in a way it later can work without repoctl; add .gitconfig in containers so it can do git pull; Fix script that cleans older chroots; Disable forcing nspr-hg; keep tweakings ufscar's rootfs; fix status showing packages as updated twice; update packages ignored hourly; add kitsuna repo as a feature

diff --git a/home/main-builder/chaotic-clean-older-chroots b/home/main-builder/chaotic-clean-older-chroots
--- a/home/main-builder/chaotic-clean-older-chroots
+++ b/home/main-builder/chaotic-clean-older-chroots
@@ -2,14 +2,15 @@
 cd /tmp/chaotic-chroot || exit
 
 _PKGS=$(~/chaotic-check-older-chroots | grep -Po 'pkg[^ ]+$')
-_ROOTS=$(echo $_PKGS | sed 's/$/\/root/')
+_ROOTS=$(echo "$_PKGS" | sed 's/$/\/root/g')
 
 [ -z "$_PKGS" ] && exit
 
+echo 'Unmounting'
 echo $_ROOTS | xargs sudo umount -Rv
+_CHECK=$(echo "$_ROOTS" | xargs sudo umount -Rv)
 
-_CHECK=$(echo $_ROOTS | xargs sudo umount -Rv)
+[ -z `echo "$_CHECK" | grep -P '.*(?<!not found|unmounted)$'` ] || exit
 
-[ -z `echo $_CHECK | grep -P '.*(?<!not found|unmounted)$'` ] || exit
-
-echo $_PKGS | xargs sudo rm --one-file-system -rf
+echo 'Deleting'
+echo "$_PKGS" | xargs sudo rm --one-file-system -rf
